---
- name: Install httpd service
  ansible.builtin.yum:
    name: httpd
    state: latest

- name: Starting and enabling httpd service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Copy html content in vhost directory
  copy:
    src: html/
    dest: "/var/www/vhosts/{{ ansible_hostname }}"

- name: Copy template on vhost.conf
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_httpd