---
- name: api call
  hosts: thefirstminion
  become: false
  vars:
    server: "https://reqres.in"
    endpoint: "/api/users?page=2"
  tasks:
  - name: uri call
    ansible.builtin.uri:
      url: "{{ server }}{{ endpoint }}"
      method: GET
      status_code: 200
      timeout: 30
    register: output

  - name: Print output
    ansible.builtin.debug:
#      var: output
      var: output.json.data