---
- name: Install httpd
  hosts: ansibleminion
  gather_facts: false
  become: true
  become_method: sudo
  become_user: ansible

  tasks:

  - name: Insall package
    yum:
      name: httpd
      state: latest

  - name: Start and enable service at boot
    service:
      name: httpd
      enabled: true
      state: started

  - name: Install firewalld
    yum:
      name: firewalld
      state: latest

  - name: Start and enable service at boot
    service:
      name: firewalld
      enabled: true
      state: started
