---
- name: Install httpd
  hosts: ansibleminion
  gather_facts: false
  become: true

  tasks:

  - name: Insall package
    yum:
      name: httpd
      state: latest

  - name: Start and enable service at boot
    service:
      name: httpd
      enabled: true
      state: started
