---
- name: Install httpd
  hosts: ansibleminion
  gather_facts: false
  become: true

  tasks:

  - name: Insall package
    yum:
      name: httpd
      state: latest

  - name: Start and enable service at boot
    service:
      name: httpd
      enabled: true
      state: started

  - name: Install firewalld
    yum:
      name: firewalld
      state: latest

  - name: Start and enable service at boot
    service:
      name: firewalld
      enabled: true
      state: started

  - name: Enable service http on firewalld
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true
