---
- name: Include task playbook
  gather_facts: false
  hosts: thelastminion
  become: true
  tasks:
  - name: Including the tasks in the tasks.yml
    include_vars: variables.yml

  - name: Install "{{ package }}"
    yum:
      name: "{{ package }}"
      state: latest
  - name: Enabling and starting "{{ service }}"
    ansible.builtin.service:
      name: "{{ service }}"
      enabled: true
      state: "{{ state }}"