---
- name: Install "{{ package }}"
  yum:
    name: "{{ package }}"
    state: latest
- name: Enabling and starting "{{ service }}"
  ansible.builtin.service:
    name: "{{ service }}"
    enabled: true
    state: "{{ state }}"